# Generated by Django 3.0 on 2019-12-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191210_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='email',
        ),
    ]
