#!/bin/bash

if [ "$CIRCLE_BRANCH" == "master" ]; then
    source deploy/production
    exit
fi

if [ "$CIRCLE_BRANCH" == "develop" ]; then
    source deploy/staging
    exit
fi

echo -e "\n[*] Skipping deployment for other branches\n"
